---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      
      # downloads dependencies
      - run: |
          yarn
          yarn global add typescript
      
      # builds distribuion folder
      - run: yarn build
