---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      # tries to restore dependencies folder from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      
      # downloads dependencies
      - run: |
          yarn
          yarn global add typescript

      # tries to save dependencies into cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # builds distribuion folder
      - run: yarn build

      # tries to save distribution folder to cache
      - save_cache:
          paths:
            - build
          key: v1-dist-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      # tries to restore dependencies folder from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: |
          yarn test

  docker-build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker

      # tries to restore dependencies folder from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # tries to restore distribution folder from cache
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "package.json" }}

      - run: |
          docker build --tag example-circleci .
          docker images

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - build
            - test
